export interface QuotationRequestInterface {
    id: number,
    number: number,
    folio: string,
    list_price: string,
    date: string,
    id_company: number,
    status: string,
    id_status: string,
    id_client: number,
    client: string,
    id_list_price: number,
    total_invest: string,
    comments: string,
}